### ISSUE TITLE
Cannot parse "^5.0.0-beta.1"

### ISSUE THREAD

**Issue by cmoine** [zafarkhaja/jsemver#54]
I suppose it is the "-beta" which makes trouble:
```
Illegal character near 'beta.1'
	at com.github.zafarkhaja.semver.expr.Lexer.tokenize(Lexer.java:218)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parse(ExpressionParser.java:86)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parse(ExpressionParser.java:43)
	at com.github.zafarkhaja.semver.Version.satisfies(Version.java:325)

```

**Comment by asarkar** [comment]
I don't think this library is maintained any more. You may want to check out https://github.com/asarkar/jsemver.

**Comment by zafarkhaja** [comment]
Hello Christophe! Sorry it took me this long to get back to you.

You're right, the current grammar doesn't support pre-release versions.

I don't know if it's still relevant to you, but I'll investigate the possibility of extending it.

**Comment by zafarkhaja** [comment]
Duplicate of #24.

**Comment by zafarkhaja** [comment]
Closing this issue in favor of #70, the progress can be followed from there.
